### ISSUE TITLE
Any chance for a captcha alike or any other overload\dos\abuse mechanism?

### ISSUE THREAD

**Issue by elico** [andyxning/shortme#3]
Any chance for a captcha alike or any other overload\dos\abuse mechanism?
Many similar services like pastebin and couple others use some defense mechanism that prevents abusive usage of the service when integrated in the public zone.

**Comment by andyxning** [comment]
@elico Yes. I agree that when a url shorten service is made public,  some technical methods need to be done to prevent abuse. 

shortme just provides an api or in some degree a lib. The web ui it contains is just a demo to show what a public url shorten service may look like. The web ui is not production ready.

I recommend end users use shortme as the internal lib and develop a web ui in their own. :)

**Comment by andyxning** [comment]
@elico I will close this issue. Feel free to reopen it if you still have some questions. :)
